import "@ant-design/v5-patch-for-react-19";
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core";
import { type Metadata } from "next";
import "./globals.css";
import theme from "./theme";

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }: { children: Readonly<React.ReactNode> }): React.ReactNode {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={theme}>{children}</MantineProvider>
            </body>
        </html>
    );
}
